services:
  mysql:
    image: mysql:8.0
    container_name: likelion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: likelion
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      start_period: 40s
      retries: 12
    networks:
      - likelion-network

  redis:
    image: redis:7.2
    container_name: likelion-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 10
    networks:
      - likelion-network

  app:
    image: ${DOCKERHUB_USERNAME}/likelion14th-be:latest
    container_name: likelion-app
    ports:
      - "8080:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/likelion
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - likelion-network

volumes:
  mysql_data:

networks:
  likelion-network:
